package main

import (
	"dts-developer-challenge/config"
	"dts-developer-challenge/routes"

	_ "dts-developer-challenge/docs" // docs generated by swag

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Task API
// @version 1.0
// @description API for managing tasks
// @host localhost:8080
// @BasePath /
func main() {
	config.ConnectDB()

	r := gin.Default()

	r.Use(cors.Default()) // Enables CORS for all headers and origins

	routes.RegisterTaskRoutes(r)

	// Swagger endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}
